fix metadata is not defined
```
500
metadata is not defined
ReferenceError: metadata is not defined
    at /src/metadata.js:10:23
```

changing `{route.label}` to `{route.title}` because the current configuration doesn't create a `label` on .md files